### ISSUE TITLE
ResLoader._release有bug

### ISSUE THREAD

**Issue by xiaocongcc** [wyb10a10/cocos_creator_framework#1]
ResLoader._release根据item.url获取cacheInfo，应该改为根据item.id获取。
如果打包md5，item.url是会带md5码的。

**Comment by wyb10a10** [comment]
md5的情况下也是可以正常工作的，建立映射的时候，依赖的是item.dependKeys，这里是带md5的url，相当于大家认知中的url都是有md5的。
