### ISSUE TITLE
打包example_ui案例到微信开发者工具环境报错

### ISSUE THREAD

**Issue by laoyuan1992** [wyb10a10/cocos_creator_framework#10]
如题，定位原因是let depItem = ccloader._cache[depKey]；depItem可能为空，尝试depItem.id会直接报错。需要在_release(）方法写  depItem&&this._release(depItem, item.id);_buildDepend(）方法写上depItem&&this._buildDepend(depItem, depItem && depItem.id ? depItem.id : refKey);

**Comment by wyb10a10** [comment]
已修复
