### ISSUE TITLE
cocos creator 2.3.0版本打开工程，导入skel文件失败

### ISSUE THREAD

**Issue by guozanhua** [wyb10a10/cocos_creator_framework#13]
E:\cocoscreator\cocoscreator\cocos_creator_framework\assets\Spine\10000\10000_Attack2.skel, message: Error: Can not find E:\cocoscreator\cocoscreator\cocos_creator_framework\assets\Spine\10000\10000_Attack2.atlas
    at I:\CocosCreator_2.3.0\resources\engine\extensions\spine\editor\spine-meta.js:56:26
    at I:\CocosCreator_2.3.0\resources\app.asar\node_modules\fire-fs\index.js:14:9
    at FSReqCallback.oncomplete (fs.js:163:21)

**Comment by wyb10a10** [comment]
收到，晚上下载一下2.3.0测试看看

**Comment by guozanhua** [comment]
你好，有修复在cocos 2.3.0版本的问题不

**Comment by wyb10a10** [comment]
cocos creator更新了spine库到3.8版本，仓库的资源并不兼容这个版本，解决方法不是修改代码，而是替换资源，用3.8版本对应的编辑器重新导出资源。
