### ISSUE TITLE
场景切换会清除常驻节点的资源

### ISSUE THREAD

**Issue by GreenGums** [wyb10a10/cocos_creator_framework#14]
`  // 2. 监听场景切换
        cc.director.on(cc.Director.EVENT_BEFORE_SCENE_LAUNCH, (scene) => {
            this._cacheScene(scene);
        });`
场景切换时，会将上一个场景的常驻节点的资源清除，这并不是我们希望看到的。

**Comment by wyb10a10** [comment]
好问题，今天抽空解决下，可能不仅仅是遍历一下场景的常驻节点，剔除这部分资源的释放

**Comment by GreenGums** [comment]
宝爷，你这边具体打算怎么做？

**Comment by wyb10a10** [comment]
挂载到场景中到常驻节点：
* 切换场景时不会自动释放
* 移除常驻节点时自动释放（使用ResKeeper，或手动清除）
运行时添加到场景中到常驻节点：
* 不属于场景的依赖资源，所以切换场景时不会自动释放
* 自己加载的资源自己释放或交给ResKeeper

所以，自己创建的自己处理，自己不想处理，可以利用ResKeeper自动处理，或者根本就不想释放它也无所谓。但拖拽上去的常驻节点，不能跟随场景释放而释放，相比在加载建立引用的时候剔除，还是释放时剔除会更合适一些，比如中间设置为了非常驻节点，释放的时候还可以自动释放。

对于已经切换场景，且没有自动释放的常驻节点资源，这里会有旧场景的引用，如果需要释放这些资源，需要清除场景的UseKey。

**Comment by wyb10a10** [comment]
另外没有勾选自动释放的资源，在场景切换的时候，也不应该自动释放

**Comment by wyb10a10** [comment]
场景自带的资源有3种情况：
* 常驻节点资源：引擎不会释放，目前ResLoader会释放，应该调整为ResLoader不会释放
* 不自动释放的资源：引擎不会释放，目前ResLoader会释放，ResLoader确实应该释放，因为引擎之所以不释放是因为这种资源被cc.loader.load动态加载了，如果切换场景时自动释放，我们的代码就可能报错，但ResLoader避免了这种情况的出现，所以ResLoader应该释放这些资源，就算有其他地方引用到，这个资源实际上也不会被释放，而如果没有其他地方引用，那么这个资源就应该被自动释放。
* 其他资源：引擎会释放，目前ResLoader会释放，这里ResLoader到释放实际上是有问题的，因为资源已经被引擎释放了，ResLoader中会有一个无效的引用！这里应该要清理这个引用。

**Comment by wyb10a10** [comment]
还存在一种情况是引擎不会释放的，就是下一个场景用到的资源，这种ResLoader应该进行useKey的替换，实际上这个问题比表面看到的，要复杂的多

**Comment by GreenGums** [comment]
我不太能看明白你说的，可能到时候看代码才知道吧。不过看到你这么热心的解答有点受宠若惊

**Comment by hszhakka** [comment]
> 我不太能看明白你说的，可能到时候看代码才知道吧。不过看到你这么热心的解答有点受宠若惊

宝爷一直都是一个热心的人。

**Comment by wyb10a10** [comment]
提交了，你看看有没有问题

**Comment by GreenGums** [comment]
我大致看了一下，你那边做了这几件事：
切换场景释放资源时剔除了常驻节点
切换场景时，将场景引用资源更新usekey
切换场景时，移除被引擎删除的失效的资源

**Comment by GreenGums** [comment]
不过我比较好奇的一点是，在我的印象中引擎是不会在切换场景时对**未勾上‘自动释放’**的场景释放资源。下面这句代码是专门为场景勾上了“自动释放”这个选项设置的吗？
`                // 判断是不是已经被场景切换自动释放的资源，是则直接移除缓存Item（失效项）
                let item = this._getResItem(this._sceneDepends[i], undefined);
                if (!item) {
                    this._resMap.delete(this._sceneDepends[i]);
                    cc.log(`delete untrack res ${this._sceneDepends[i]}`);
                }`

**Comment by wyb10a10** [comment]
是的，你看这个修改是否解决了你的问题，如果解决了，我就可以关闭这个issue了
