### ISSUE TITLE
releasRes会释放item以及item的依赖资源，但是resLeakChecker只会对item进行进行移除，这是否会导致resLeakChecker的计算不准确？

### ISSUE THREAD

**Issue by GreenGums** [wyb10a10/cocos_creator_framework#15]
releasRes会释放item以及item的依赖资源，但是resLeakChecker只会对item进行进行移除，这是否会导致resLeakChecker的计算不准确？如下注释所示:
`    public releaseRes() {
        let resArgs: ReleaseResArgs = ResLoader.makeReleaseResArgs.apply(this, arguments);
        let item = this._getResItem(resArgs.url, resArgs.type);
        if (!item) {
            console.warn(`releaseRes item is null ${resArgs.url} ${resArgs.type}`);
            return;
        }
        // cc.log(arguments);
        let cacheInfo = this.getCacheInfo(item.id);
        if (resArgs.use) {
            cacheInfo.uses.delete(resArgs.use)
            if (this.resLeakChecker) {
                this.resLeakChecker.logRelease(item.id, resArgs.use);//会将item 从resLeakChecker的_log里面移除
            }
        }

        if (cacheInfo.uses.size == 0) {
            this._release(item, item.id);//递归释放item资源以及item的依赖
        }
    }`

**Comment by wyb10a10** [comment]
并不会，这里主要记录你调用load的堆栈，在合适的时候可以打印出当前未释放的资源是在哪里load的，是否有应该释放而没有释放的资源。
