### ISSUE TITLE
Resloader里的_cacheItem缓存了一个use，导致ResKeeper里执行autoReleaseRes时，无法将资源缓存加入autoRes中

### ISSUE THREAD

**Issue by Yokan-Jan** [wyb10a10/cocos_creator_framework#17]
用uimanager打开一个界面，Resloader里的_cacheItem缓存了一个use。然后UIManager执行uiview.autoReleaseRes时会报key已经存在，导致资源缓存无法存进autoRes中，导致无法自动释放

**Comment by wyb10a10** [comment]
已解决
