### ISSUE TITLE
请问数据层调用UI的正确姿势是什么样子的

### ISSUE THREAD

**Issue by FOUNDXFUND** [wyb10a10/cocos_creator_framework#18]
写了个类，里面需要操作UI层，但是一引用就报错：load script [./ResLoader] failed : TypeError: ResKeeper_1.default is not a constructor

把这个类文件，放到uI同个目录，就不报错了。。

目前结构：
script
 ---ui
 ---mgr

mgr里面写了个Test.ts:
```
import UIGameMain from "../ui/uiviews/UIGameMain"
export class SignInMgr {
    test() {
        UIGameMain.Ins.onClickSign()
    }
}
```

请问一下。。。是不是我姿势不对。。。

**Comment by wyb10a10** [comment]
应该是uiManager.getUI(uiId);去拿而不是用单例
另外 *default is not a constructor，可以试一下 
`import {UIGameMain} from "../ui/uiviews/UIGameMain"`

**Comment by FOUNDXFUND** [comment]
uiManager.getUI(uiId)用这个依然报TypeError: ResKeeper_1.default is not a constructor 。。。。
我都怀疑是不是我项目有毒，下你的完整项目添加文件改就不报。

**Comment by wyb10a10** [comment]
https://stackoverflow.com/questions/42652423/error-default-is-not-a-constructor
看看这个，调整一下import的姿势看看

**Comment by FOUNDXFUND** [comment]
新建一个空目录，放进去”解决“问题了,我想应该是我其他代码有问题吧,谢谢楼主,可以关掉了...

**Comment by wyb10a10** [comment]
除了import的问题，我建议，数据层不要主动去操作UI层，数据模型你可以作为单例，UI层和逻辑层都可以去访问数据，这样代码会更解耦，更好维护。

另外，每个模型的数据更新，可能是由网络过来的，也可能是本地的更新，这些更新要通知到界面刷新，我建议使用事件机制！

比如金币变化，我们可能会有很多界面需要展示金币，又有很多个地方会去加减金币，如果使用主动操作UI的方式，那么耦合性就很强，特别难以维护，如果用事件机制，则在每个界面监听金币变化的事件做刷新就可以了，而对于一些不需要及时刷新的界面，可能在onTop回调中，当界面置顶的时候，去刷新一下。

**Comment by wyb10a10** [comment]
我又换了一个写法，你看看还有没有reskeeper的那个问题
