### ISSUE TITLE
cc.loader.load接口没有？

### ISSUE THREAD

**Issue by yksalun** [wyb10a10/cocos_creator_framework#2]
ResLoader没有调用cc.loader.load接口，这个接口用于加载远程资源或者是本地用户目录的资源，在移动端上还是很有必要的，希望可以加上这个接口。

**Comment by wyb10a10** [comment]
安排～

**Comment by wulei** [comment]
ResLoader上如果有，就没法知道他的引用属于哪个view了吧？可以参照ui里面的自己makekey后管理。

**Comment by Bush16** [comment]
你是不是发错人了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Leo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午3:43
收件人:&nbsp;"wyb10a10/cocos_creator_framework"<cocos_creator_framework@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wyb10a10/cocos_creator_framework] cc.loader.load接口没有？ (#2)




ResLoader上如果有，就没法知道他的引用属于哪个view了吧？可以参照ui里面的自己makekey后管理。

**Comment by wyb10a10** [comment]
resLoader.loadRes 已支持加载远程图片，ResExample新增了一对测试远程资源加载卸载的接口调用示例，在检测到要加载的资源不属于内置资源时，会自动调用load方法去加载资源。
