### ISSUE TITLE
原生平台内存飙升

### ISSUE THREAD

**Issue by BadworkerN** [wyb10a10/cocos_creator_framework#21]
exameple_res 打包android 反复加载和释放resloader的资源,内存一直上升, 
![内存](https://user-images.githubusercontent.com/16665452/89869441-f05fe980-dbe6-11ea-9586-751b8d4ea9ff.png)

**Comment by wyb10a10** [comment]
你用的是什么版本的creator？

**Comment by BadworkerN** [comment]
2.3.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wyb10a10/cocos_creator_framework"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 下午3:28
收件人:&nbsp;"wyb10a10/cocos_creator_framework"<cocos_creator_framework@noreply.github.com&gt;;
抄送:&nbsp;"聂华吕"<381900623@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wyb10a10/cocos_creator_framework] 原生平台内存飙升 (#21)





 
你用的是什么版本的creator？

**Comment by wyb10a10** [comment]
从示意图上看，基本上是图片的内存占用增加了，这里应该是和GC有关，而不是真正的泄露，比如我们加载一个Texture，再释放它，重复执行这个操作，如果没有触发到js的垃圾回收，实际上这些东西应该是在内存中的。你可以直接用原生接口加载和释放，做一个测试

**Comment by BadworkerN** [comment]
定时主动调用gc也不能导致内存降下来，这部分内存一直驻留，只有不销毁节点才能保证内存不再增长


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 宝爷 <notifications@github.com&gt;
发送时间: 2020年8月12日 22:55
收件人: wyb10a10/cocos_creator_framework <cocos_creator_framework@noreply.github.com&gt;
抄送: BadworkerN <381900623@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[wyb10a10/cocos_creator_framework] 原生平台内存飙升 (#21)





 
从示意图上看，基本上是图片的内存占用增加了，这里应该是和GC有关，而不是真正的泄露，比如我们加载一个Texture，再释放它，重复执行这个操作，如果没有触发到js的垃圾回收，实际上这些东西应该是在内存中的。你可以直接用原生接口加载和释放，做一个测试

**Comment by laoyuan1992** [comment]
我的也是2.3.3，发布安卓，内存存在问题。资源贴图有释放错误的问题,

**Comment by wyb10a10** [comment]
@laoyuan1992 是什么错误呢？

**Comment by wyb10a10** [comment]
https://forum.cocos.org/t/cocos-creator-2-3-3/91293 在2.3.3版本找到这段话，应该是要额外destroy节点

```js
如原先手动从场景中移除的节点，在不需要用到的时候也需要统一 `destroy()`：
// 假设 testNode 是场景中的某个节点，若之前被手动移出场景了，如
testNode.parent = null;
// 或者
testNode.removeFromParent(true);
// 或者
parentNode.removeChild(testNode);
// 若往后 testNode 还会再次用到，则无需手动 destroy 该节点
// 否则应该手动调用
testNode.destroy();
```
