### ISSUE TITLE
支持2.4.3吗?

### ISSUE THREAD

**Issue by sdfasffsdf** [wyb10a10/cocos_creator_framework#23]
支持2.4.3吗?

**Comment by bournes** [comment]
宝爷已经无心与这个项目的更新了！！

**Comment by wyb10a10** [comment]
> 支持2.4.3吗?

你切到creator 2.4.2分支，应该跟2.4.3差别不大

> 宝爷已经无心与这个项目的更新了！！

接下来会开始频繁更新了，资源框架部分来一个大重构
