### ISSUE TITLE
NetNode.ts 的自动重连貌似有一句写错了的代码

### ISSUE THREAD

**Issue by didoupt** [wyb10a10/cocos_creator_framework#24]
在NetNode.ts的第84行：
if (this._connectOptions == null) {
                options.autoReconnect = options.autoReconnect
            }
根据我我理解，宝爷在这里应该是想在第一次连接的时候设置自动重连的次数，所以正确的代码应该是这样色的：
if (this._connectOptions == null) {
                this._autoReconnect = options.autoReconnect
            }

**Comment by wyb10a10** [comment]
嗯，没错，要不要提个pr

**Comment by didoupt** [comment]
额，我没有fork

**Comment by didoupt** [comment]
我只是下载下来学习，偶然间发现的

**Comment by wyb10a10** [comment]
那我改一下？

**Comment by didoupt** [comment]
好的，宝爷秒回，我好激动，啊哈哈哈

**Comment by wyb10a10** [comment]
已经修复，祝你生活愉快
