### ISSUE TITLE
宝爷的频繁更新什么时候能看到！！！

### ISSUE THREAD

**Issue by bournes** [wyb10a10/cocos_creator_framework#25]
todo: 热更新
todo: 新手引导框架
比较期待这些使用功能！！！

**Comment by wyb10a10** [comment]
今天

**Comment by bournes** [comment]
坐等！！！

**Comment by gs183900** [comment]
宝爷 期待

**Comment by BrokenTooth1989** [comment]
这几天有点多啊,666666

**Comment by qx** [comment]
2.4.3会升级吗@wyb10a10

**Comment by wyb10a10** [comment]
> 2.4.3会升级吗@wyb10a10

这是下一步要做的，先把接口调整好，然后升级框架到2.4.3以上，让框架同时适配新旧版本

**Comment by bournes** [comment]
宝爷。官方已经更新到3.0正式版了

**Comment by wyb10a10** [comment]
> 宝爷。官方已经更新到3.0正式版了

安排中，重构后已经是考虑了兼容3.0的了，最近特别忙，要3月3号之后才有时间继续搞！

**Comment by wyb10a10** [comment]
> 宝爷。官方已经更新到3.0正式版了

今天开始搞一下3.0，大家节日快乐

**Comment by bournes** [comment]
坐等

**Comment by bournes** [comment]
> > 宝爷。官方已经更新到3.0正式版了
> 
> 今天开始搞一下3.0，大家节日快乐

宝爷昨天貌似没有更新3.0哦！

**Comment by wyb10a10** [comment]
实在是面目全非了，现在还没跑起来呢

**Comment by bournes** [comment]
宝爷转眼就过去6天了。。3.0的有进度吗？

**Comment by wyb10a10** [comment]
改动很大哦，除了接口的变动，ts的检查也非常严格，之前很多代码注入之类的方式会引发语法错误，虽然直接`// @ts-nocheck`很方便，但我还是选择让代码能在最严格的检查下运行。最后感谢你的关注，代码大概调整了80%了，剩下20%本周应该可以弄完。

**Comment by bournes** [comment]
嗯嗯。。。我会等你的！！！

**Comment by bournes** [comment]
宝爷今天是周四了哦！明天是不是可以看到你的版本更新了呢！！好期待！！！对了，。
todo: 热更新
todo: 新手引导框架  这两个也好期待！！

**Comment by wyb10a10** [comment]
这一周忙到都没有时间写代码，可能要到今晚才有时间写，热更是在cocos的热更基础上简单封装的一套，新手引导晓衡兄好像有发过一个设计的还不错的新手引导，你可以了解一下

**Comment by bournes** [comment]
晓衡兄 的GIT链接来一个！！！

**Comment by wyb10a10** [comment]
https://github.com/ShawnZhang2015/GodGuide
https://www.cnblogs.com/creator-star/p/11800956.html
调整差不多了，明天可以提交了

**Comment by wyb10a10** [comment]
这个讨论帖先close了
