### ISSUE TITLE
宝爷你的UIManager为什么不写成单例呢

### ISSUE THREAD

**Issue by bournes** [wyb10a10/cocos_creator_framework#26]
export let uiManager: UIManager = new UIManager();   

为什么不写成 

export let UIMgr = UIManager.getInstance();

**Comment by wyb10a10** [comment]
其实这里两种写法我觉得区别不大，之前直接new有一个原因是有些构造函数中的全局处理，希望在程序启动时就初始化好，但现在不存在这个问题了。
如果上层使用的是uiManager，它是new出来的或者是getInstance得到的其实并不重要，比如在CC3.0的源码中，像AssetManager这种单例，也是直接new出来的。
