### ISSUE TITLE
prefab实例化的时候资源应该如何管理？

### ISSUE THREAD

**Issue by yksalun** [wyb10a10/cocos_creator_framework#3]
如果调用了ResLoader.loadRes加载了一个prefab A，则A和A所引用的资源 引用计数都会+1，如果这时候我instantiate出了A1，则A1和A1所引用的资源好像没有被管理，请问这部分资源应该如何纳入ResLoader管理呢？

**Comment by wulei** [comment]
如果A会instantate，说明肯定是有脚本的，必定继承UIView，然后可以在onDestory的时候调用自动释放。

**Comment by wulei** [comment]
还有个建议instantiate的node可以加一个标记
`
let node = cc.instantiate(prefab)
node['__SELF'] = ture
`
然后在destory的时遍历所有节点有 __SELF 标记的调用一下 node.destory() 否则加载进uiview上的应该内存有问题

不过是我个人见解

**Comment by Bush16** [comment]
所以你是不是发错人了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Leo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午3:46
收件人:&nbsp;"wyb10a10/cocos_creator_framework"<cocos_creator_framework@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wyb10a10/cocos_creator_framework] prefab实例化的时候资源应该如何管理？ (#3)




还有个建议instantiate的node可以加一个标记
 let node = cc.instantiate(prefab) node['__SELF'] = ture
 然后在destory的时遍历所有节点有 __SELF 标记的调用一下 node.destory() 否则加载进uiview上的应该内存有问题
 
不过是我个人见解

**Comment by wyb10a10** [comment]
这个也安排一下，我会写一个新的示例，把我认为比较合适的解决方案提交。

**Comment by wyb10a10** [comment]
今天花了一天的时间，仔细思考了如何在兼容效率、编写复杂度的情况下实现赋值、Prefab实例化的自动内存管理。具体可以看我新提交的example_res_keeper场景，代码位于ResKeeperExample.ts。

实例化使用ResUtil.instantiate( prefab )，比如实例化了100个对象，会自动在100个对象destroy之后释放资源，如果这个prefab没有被其它地方依赖或者use的话。需要注意的是prefab需要是通过resloader加载的Prefab。

ResKeeper是一个简单的轻量级方案，包括一个spriteframe希望赋值给多个对象，然后自动管理spriteframe的释放，都可以交给ResKeeper组件。

暂时先说这么多吧，最近还有几个资源管理的有用特性需要开发，相信会对大家有所帮助！新年快乐~
