### ISSUE TITLE
宝爷初心已忘了吗？

### ISSUE THREAD

**Issue by bournes** [wyb10a10/cocos_creator_framework#30]
好久没有看到更新了？

**Comment by wyb10a10** [comment]
最近3个月，有很多事情，需要优先处理
除了工作和带娃之外，另外有一个开源项目也投入了很多精力，前段时间因为自己成为阻塞项目进度的瓶颈了，所以把所有业余时间的精力都投入到这个项目中，现在虽然还需要我这边继续投入，但项目的其他人已经可以运作起来了，五月份我会恢复更新，有一些新的想法，另外，我还邀请了一个朋友一起维护开发。
本来是想在四月份恢复更新的，但还是太忙了，应该越到后面，这里的更新会更稳定一些，看到你的呼唤，值得我花更多的时间在这上面
