### ISSUE TITLE
请问下 这个在哪设置下websocket的Header呢？

### ISSUE THREAD

**Issue by weichangyu** [wyb10a10/cocos_creator_framework#33]

**Comment by wyb10a10** [comment]
websocket的api没有提供这个支持，你是什么场景下的需求呢？

**Comment by weichangyu** [comment]
> websocket的api没有提供这个，你是什么场景下的支持需求呢？

谢谢，解决了。new websocket 的时候提供一个 protocols参数，但由于我后端框架的问题，导致设置这个参数会报错，连接不上，我就以为这个参数不是header里面的东西。
