### ISSUE TITLE
3.x的一点疑问

### ISSUE THREAD

**Issue by cyq33** [wyb10a10/cocos_creator_framework#35]
宝爷，这里有个问题，能请教你一下吗？，我看您在3.x版本中的 这里有多加了这一句。我清理的时候，看到新增的资源没有清理。多加的这里是做什么用的？另外我看了2.x。这里是没有引用的。这句注释之后。清理就成功了。看了下代码。这里也是addRef（）了一下。
![微信图片_20220831112537](https://user-images.githubusercontent.com/86040766/187586003-8c2d096f-cd11-4376-8f76-8026ad9d0bdd.jpg)

**Comment by wyb10a10** [comment]
这里测试用的，用于追踪资源的引用计数

**Comment by cyq33** [comment]
好勒，了解了。谢谢宝爷解惑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wyb10a10/cocos_creator_framework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月4日(星期天) 凌晨0:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wyb10a10/cocos_creator_framework] 3.x的一点疑问 (Issue #35)





 
这里测试用的，用于追踪资源的引用计数
