### ISSUE TITLE
loadDir和loadArray动态加载的资源如果管理？

### ISSUE THREAD

**Issue by laoyuan1992** [wyb10a10/cocos_creator_framework#4]
看了你写的例子，现在用你的组件可以有效的管理释放资源了，但是基于项目的需求，我们有时候不一定是通过loadRes动态加载资源的。请问loadDir和loadArray这两个方法动态加载的资源如果有效的管理起来？

**Comment by wyb10a10** [comment]
安排，现在就加

**Comment by wyb10a10** [comment]
loadResArray 接口已经提交了，loadDir 周末再看看

**Comment by wyb10a10** [comment]
添加Array、Dir的批量加载资源接口，以及释放资源接口，并在ResExample中添加了测试代码
