### ISSUE TITLE
打上引用标记时未考虑资源循环引用问题，导致程序陷入死循环

### ISSUE THREAD

**Issue by GreenGums** [wyb10a10/cocos_creator_framework#6]
预制father上面有两个子节点A、B，A、B上面各引用了预制a、b。a预制的脚本上挂了b预制，b脚本上挂了a预制。这样我在加载预制资源father的时候，_buildDepend()会陷入死循环
目前我的解决办法是定义一个数组记录已经打上标记的资源，打上标记的时候跳过数组内的元素。代码如下：`  /**已经被打上标记的 */
    addedDepKeyArray:any[] = [];
    private _buildDepend(item: any, refKey: string) {
        // 反向关联引用（为所有引用到的资源打上本资源引用到的标记）
        if (item && item.dependKeys && Array.isArray(item.dependKeys)) {
            for (let depKey of item.dependKeys) {
                let index = this.addedDepKeyArray.indexOf(depKey);
                if(index!==-1){
                    cc.log('已经打上标记的不再打上标记');
                    cc.log(depKey);
                    continue;
                }
                this.addedDepKeyArray.push(depKey);
                // 记录该资源被我引用
                this.getCacheInfo(depKey).refs.add(refKey);
                cc.log(`${depKey} ref by ${refKey}`);
                let ccloader: any = cc.loader;
                let depItem = ccloader._cache[depKey]
                this._buildDepend(depItem, refKey);
            }
        }
    }`
build之前置空数组
` private _finishItem(url: string, assetType: typeof cc.Asset, use?: string) {
        let item = this._getResItem(url, assetType);
        if (item && item.id) {
            this.addedDepKeyArray.length = 0;//制空
            this._buildDepend(item, item.id);
        } else {
            cc.warn(`addDependKey item error! for ${url}`);
        }
        cc.log('_buildDepend Finish');
        // 添加自身引用
        if (item) {
            let info = this.getCacheInfo(item.id);
            info.refs.add(item.id);
            if (use) {
                info.uses.add(use);
            }
        }
    }`
同样的，release资源的时候也会有循环引用的问题

**Comment by GreenGums** [comment]
在此，再次感谢宝爷的分享。目前我的项目使用你的释放已经节省了不少内存

**Comment by wyb10a10** [comment]
了解了，我想了一下，使用了更一个简单的方法 _buildDepend 中，先判断refs中是否已经添加过了，如果添加过了，就直接跳过。

**Comment by GreenGums** [comment]
释放的时候貌似也有这个bug，你这边再看一下

**Comment by wyb10a10** [comment]
释放的也修复了，稍后提交
