### ISSUE TITLE
龙骨动画在oppo平台上无法正确释放

### ISSUE THREAD

**Issue by GreenGums** [wyb10a10/cocos_creator_framework#7]
检测item资源是否被场景依赖时是通过item的url进行检测。但在有些平台item的url会带上md5，因此会检测没有被场景依赖，从而导致不该释放的资源被释放。
目前测出来的：龙骨动画在oppo runtime2.6必现，vivo平台貌似也会出现。
不知道宝爷你这边有没有办法对item的url进行去除md5办法？

**Comment by GreenGums** [comment]
private _isSceneDepend(itemUrl) {
        let scene: any = cc.director.getScene();
        if(!scene){ 
            return false;
        }
        let len = scene.dependAssets.length;
        for (let i = 0; i < len; ++i) {
            if (scene.dependAssets[i] == itemUrl)//itemUrl带上了md5，而左边没有
                return true;
        }
        return false;
    }

**Comment by GreenGums** [comment]
目前我移除md5的操作如下：
`
    removeMD5(str:string){
        let strArr = str.split('.');
        if(strArr.length<=2){
            return str;
        }
        if(strArr.length===3){
            return strArr[0]+'.'+strArr[2];
        }
        else{
            cc.log(`error！，can not remove md5：${str}`);
            return null;
        }
    }`
在oppo平台上已解决不能正确释放龙骨动画依赖资源的问题

**Comment by wyb10a10** [comment]
if (this._isSceneDepend(item.url)) ->  if (this._isSceneDepend(item.id)) 修复

**Comment by GreenGums** [comment]
> if (this._isSceneDepend(item.url)) -> if (this._isSceneDepend(item.id)) 修复
果然你这边修复起来比我要容易得多。我整老半天你几秒钟就搞定了。

**Comment by wyb10a10** [comment]
欢迎提issue！过年可以好好写一写cocos的代码和文章了
